#! /usr/bin/env python
DB_NAME               = './sqlite-latest.sqlite'
QUERY_STRING          = r"SELECT a.typeID AS 'invTypes.typeID', a.typeName AS 'invTypes.typeName', e.groupName, a.mass, a.volume, a.capacity, d.categoryName AS 'dgmAttributeCategories.categoryName', c.attributeName AS 'dgmAttributeTypes.attributeName', c.displayName, b.valueInt, b.valueFloat, f.raceName FROM invTypes AS a INNER JOIN dgmTypeAttributes AS b ON (a.typeID = b.typeID) INNER JOIN dgmAttributeTypes AS c ON (b.attributeID = c.attributeID) INNER JOIN dgmAttributeCategories as d ON (c.categoryID = d.categoryID) INNER JOIN invGroups as e ON (a.groupID = e.groupID) INNER JOIN chrRaces as f ON (a.raceID = f.raceID) WHERE e.categoryID = 6 AND c.attributeName NOT IN ('warpFactor', 'powerLoad', 'cpuLoad', 'powerToSpeed', 'mainColor', 'maxPassenger', 'propulsionGraphicID', 'gfxBoosterID') AND a.typeID NOT IN (34457, 34459, 34467, 34471) AND a.typeName NOT LIKE ('?%') ORDER BY a.TypeName, d.CategoryName, c.AttributeName"
SHUTTLE_NAMES         = ['Amarr Shuttle', 'Caldari Shuttle', 'Gallente Shuttle', 'Minmatar Shuttle']
DESIRED_PARTIALS      = ['Navy', 'Fleet']
DESIRED_ATTRIBUTES    = {"armorHP": "armor_hitpoints", "capacitorCapacity": "capacitor_capacity", "rechargeRate": "capacitor_recharge_rate", "droneBandwidth": "drone_bandwidth", "droneCapacity": "drone_capacity", "cpuOutput": "cpu", "hiSlots": "high_slots", "lowSlots": "low_slots", "medSlots": "med_slots", "launcherSlotsLeft": "launcher_hardpoints", "powerOutput": "powergrid", "rigSlots": "rig_slots", "turretSlotsLeft": "turret_hardpoints", "techLevel": "tech_level", "requiredSkill1": "required_skill", "requiredSkill1Level": "required_skill_level", "shieldCapacity": "shield_hitpoints", "agility": "inertia_modifier", "maxVelocity": "max_velocity", "hp": "structure_hitpoints", "maxLockedTargets": "max_targets", "maxTargetRange": "max_targeting_range", "scanGravimetricStrength": "gravimetric_sensor_strength", "scanLadarStrength": "ladar_sensor_strength", "scanMagnetometricStrength": "magnetometric_sensor_strength", "scanRadarStrength": "radar_sensor_strength", "scanResolution": "scan_resolution", "signatureRadius": "signature_radius", "requiredSkill2": "required_advanced_skill", "requiredSkill2Level": "required_advanced_skill_level"}
FRIGATE_CLASSES       = ["Frigate", "Assault Frigate", "Interceptor", "Covert Ops", "Electronic Attack Ship"]
DESTROYER_CLASSES     = ["Destroyer", "Tactical Destroyer"]
CRUISER_CLASSES       = ["Cruiser", "Heavy Assault Cruiser", "Heavy Interdiction Cruiser", "Logistics", "Recon Ship", "Strategic Cruiser"]
BATTLECRUISER_CLASSES = ["Battlecruiser", "Command Ship"]
BATTLESHIP_CLASSES    = ["Battleship", "Black Ops", "Maurader"]
